# Generated by Django 4.1.5 on 2023-01-07 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=2)),
                ('major', models.CharField(max_length=100)),
            ],
        ),
    ]
